# Configuración para Fly.io
app = "ssl-monitoring-n8n"
primary_region = "mia"

[build]
  dockerfile = "Dockerfile"

[env]
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "admin"
  N8N_BASIC_AUTH_PASSWORD = "crecemos2024"
  GENERIC_TIMEZONE = "America/Bogota"
  N8N_HOST = "0.0.0.0"
  N8N_PORT = "5678"

[[services]]
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[experimental]
  auto_rollback = true
