# Configuración optimizada para Fly.io
app = "ssl-monitoring-n8n"
primary_region = "mia"  # Miami (más cerca de Colombia)

[build]
  dockerfile = "Dockerfile.simple2"

[env]
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "admin"
  N8N_BASIC_AUTH_PASSWORD = "crecemos2024"
  GENERIC_TIMEZONE = "America/Bogota"

[[services]]
  internal_port = 5678
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[experimental]
  auto_rollback = true
